### ISSUE TITLE
Node v4 support

### ISSUE THREAD

**Issue by claudiopetrini** [mceachen/exiftool-vendored.js#1]
I've noticed that there's a branch named `node4` but it doesn't seems to work throwing the following error : 
```
path/node_modules/exiftool-vendored/dist/exiftool.js:24
    constructor(maxProcs = 1) {
                         ^
SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/claudiopetrini/Desktop/test/index-exiftools.js:1:80)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
```

In the `package.json` the supported engine is still `"node": ">= 6.4.0"`, is it just an old branch or is there a plan to support Node v4?

**Comment by mceachen** [comment]
TBH, I was just being conservative when I set this up (and I'm running on node 6+). There shouldn't be anything exotic that can't work in node 4, as long as I transpile to es5. 

I've exhumed the branch and we'll see if Travis tests pass. Could you try the branch out and see if it works before I publish 2.10.0?

**Comment by mceachen** [comment]
Builds are successful, I'm pushing v2.10 now. Have fun with Node 4.

**Comment by claudiopetrini** [comment]
Thank you for you super fast response, it works perfectly!
