### ISSUE TITLE
How to catch errors, or remove them ?

### ISSUE THREAD

**Issue by thib3113** [mceachen/exiftool-vendored.js#28]
I actually get an error, coming from a corrupted jpeg .

The problem is, I didn't find the way to catch the way to "catch" the error, and not display it to the console .

So, I get this error (on the console) : 
```
BatchProcess(9328).onError() { source: 'stderr.data',
  task:
   '-AllDates=2018-08-14T12:26:58.000\n-overwrite_original\n-charset\nfilename=utf8\n-codedcharacterset=utf8\nC:\\Users\\thib3\\repos\\timer-correct\\photos\\test\\AFS2018-223.JPG\n-ignoreMinorErrors\n-execute\n',
  error:
   Error: stderr.data: Bad InteropIFD offset for InteropIndex - C:/Users/thib3/repos/timer-correct/photos/test/AFS2018-223.JPG
       at BatchProcess.<anonymous> (C:\Users\thib3\repos\timer-correct\node_modules\batch-cluster\dist\BatchProcess.js:312:25)
       at step (C:\Users\thib3\repos\timer-correct\node_modules\batch-cluster\dist\BatchProcess.js:32:23)
       at Object.next (C:\Users\thib3\repos\timer-correct\node_modules\batch-cluster\dist\BatchProcess.js:13:53)
       at C:\Users\thib3\repos\timer-correct\node_modules\batch-cluster\dist\BatchProcess.js:7:71
       at new Promise (<anonymous>)
       at __awaiter (C:\Users\thib3\repos\timer-correct\node_modules\batch-cluster\dist\BatchProcess.js:3:12)
       at BatchProcess.onError (C:\Users\thib3\repos\timer-correct\node_modules\batch-cluster\dist\BatchProcess.js:306:16)
       at Socket.<anonymous> (C:\Users\thib3\repos\timer-correct\node_modules\batch-cluster\dist\BatchProcess.js:81:26)
       at Socket.emit (events.js:182:13)
       at addChunk (_stream_readable.js:283:12) }
Task.reject() { cmd:
   '-AllDates=2018-08-14T12:26:58.000\n-overwrite_original\n-charset\nfilename=utf8\n-codedcharacterset=utf8\nC:\\Users\\thib3\\repos\\timer-correct\\photos\\test\\AFS2018-223.JPG\n-ignoreMinorErrors\n-execute\n',
  error:
   Bad InteropIFD offset for InteropIndex - C:/Users/thib3/repos/timer-correct/photos/test/AFS2018-223.JPG
       at Socket.<anonymous> (C:\Users\thib3\repos\timer-correct\node_modules\batch-cluster\dist\BatchProcess.js:81:49)
       at Socket.emit (events.js:182:13)
       at addChunk (_stream_readable.js:283:12)
       at readableAddChunk (_stream_readable.js:264:11)
       at Socket.Readable.push (_stream_readable.js:219:10)
       at Pipe.onread (net.js:635:20) }
file .\1532926361.jpg was corrected and moved to C:\Users\thib3\repos\timer-correct\photos\test\1532925761.jpg (3/4)
BatchProcess(12396).onError() { source: 'stderr.data',
  task:
   '-AllDates=2018-08-14T12:26:58.000\n-overwrite_original\n-charset\nfilename=utf8\n-codedcharacterset=utf8\nC:\\Users\\thib3\\repos\\timer-correct\\photos\\test\\AFS2018-223.JPG\n-ignoreMinorErrors\n-execute\n',
  error:
   Error: stderr.data: Bad InteropIFD offset for InteropIndex - C:/Users/thib3/repos/timer-correct/photos/test/AFS2018-223.JPG
       at BatchProcess.<anonymous> (C:\Users\thib3\repos\timer-correct\node_modules\batch-cluster\dist\BatchProcess.js:312:25)
       at step (C:\Users\thib3\repos\timer-correct\node_modules\batch-cluster\dist\BatchProcess.js:32:23)
       at Object.next (C:\Users\thib3\repos\timer-correct\node_modules\batch-cluster\dist\BatchProcess.js:13:53)
       at C:\Users\thib3\repos\timer-correct\node_modules\batch-cluster\dist\BatchProcess.js:7:71
       at new Promise (<anonymous>)
       at __awaiter (C:\Users\thib3\repos\timer-correct\node_modules\batch-cluster\dist\BatchProcess.js:3:12)
       at BatchProcess.onError (C:\Users\thib3\repos\timer-correct\node_modules\batch-cluster\dist\BatchProcess.js:306:16)
       at Socket.<anonymous> (C:\Users\thib3\repos\timer-correct\node_modules\batch-cluster\dist\BatchProcess.js:81:26)
       at Socket.emit (events.js:182:13)
       at addChunk (_stream_readable.js:283:12) }
Task.reject() { cmd:
   '-AllDates=2018-08-14T12:26:58.000\n-overwrite_original\n-charset\nfilename=utf8\n-codedcharacterset=utf8\nC:\\Users\\thib3\\repos\\timer-correct\\photos\\test\\AFS2018-223.JPG\n-ignoreMinorErrors\n-execute\n',
  error:
   Bad InteropIFD offset for InteropIndex - C:/Users/thib3/repos/timer-correct/photos/test/AFS2018-223.JPG
       at Socket.<anonymous> (C:\Users\thib3\repos\timer-correct\node_modules\batch-cluster\dist\BatchProcess.js:81:49)
       at Socket.emit (events.js:182:13)
       at addChunk (_stream_readable.js:283:12)
       at readableAddChunk (_stream_readable.js:264:11)
       at Socket.Readable.push (_stream_readable.js:219:10)
       at Pipe.onread (net.js:635:20) }
``` 

I tried some options : 
```js
let currExiftool = new ExifTool(Object.assign(exiftool.options, {
    exiftoolArgs      : ["overwrite_original"],
    minorErrorsRegExp: /InteropIFD/gi //this doesn't resolve the problem
}));
//this debugger is not called, so I think it's not called
currExiftool.rejectTaskOnStderr = () => {debugger; return true};
```

 
```js
await currExiftool.write(file, {AllDates: DateTimeOriginal.toString()}, ["-overwrite_original"]).catch(err=>console.log("catched"));
```
Doesn't throw error, but log `catched` after the console.log .

So my question is : 
 How to get this error ? (not in the console), or how to hide this error please ?

**Comment by mceachen** [comment]
Which version are you using? I believe the latest (6.1.1, from yesterday afternoon) addresses this issue.

**Comment by thib3113** [comment]
@mceachen yes, i'm using the latest ( 6.1.1 )

**Comment by mceachen** [comment]
Can you attach the image, or email it to me if you don't want to make it public?

**Comment by thib3113** [comment]
No problem, In fact the image is unreadable for me, Here is a little mock to reproduce : 
[timer-correct.zip](https://github.com/mceachen/exiftool-vendored.js/files/2299819/timer-correct.zip)

**Comment by mceachen** [comment]
The errors going to console can be delivered some place else by using setLogger(). See https://batch-cluster.js.org/globals.html#setlogger and https://github.com/mceachen/batch-cluster.js/blob/master/src/_chai.spec.ts#L20 for example code.

Your call to `currExiftool.rejectTaskOnStderr` isn't valid--that's only in scope to the constructor option.

Just using the node REPL, I can repro the error with this:

```js
const ExifTool = require("exiftool-vendored").ExifTool
const et = new ExifTool({minorErrorsRegExp:  /error|warning/i}) // < this demotes all errors, it's not what you want, probably
et.write("AFS2018-223.JPG", {AllDates: "2018:08:18 12:39:39"}).then(console.dir).catch(console.dir)
```
You'll see that ExifTool isn't writing the dates because the tags are in a bad state for that file. You can try first repairing the file:

```js
et.rewriteAllTags("AFS2018-223.JPG", "repaired.jpg").then(console.dir)
et.write("repaired.jpg", {AllDates: "2018:08:18 12:39:39"}).then(console.dir).catch(console.dir)
```
That worked on my machine.

**Comment by mceachen** [comment]
Would you rather the library not write any errors to console by default? I'm afraid people will not know that errors are happening, otherwise. I'd appreciate your thoughts.

**Comment by thib3113** [comment]
@mceachen In my opinion, libraries will never write to console .

The end developer need to handle that .

I think, the best is to throw an exception if you have a fatal error . 

Thank you for the sample, I'll try that :) .

**Comment by mceachen** [comment]
I agree that fatal errors should raise, but unfortunately in this case it's
not clear which problems are warnings and which are errors. Even when
ExifTool says "warning", it's sometimes a fatal problem with the file, and
sometimes when it says "error," it's an ignorable problem with some obscure
tag.

I guess I could disable the console logging by default, though?

On Aug 18, 2018 12:56 PM, "thibaut severac" <notifications@github.com>
wrote:

@mceachen <https://github.com/mceachen> In my opinion, libraries will never
write to console .

The end developer need to handle that .

I think, the best is to throw an exception if you have a fatal error .

Thank you for the sample, I'll try that :) .

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/mceachen/exiftool-vendored.js/issues/28#issuecomment-414082645>,
or mute the thread

**Comment by thib3113** [comment]
`I guess I could disable the console logging by default, though?`
In my opinion, yes pls .

About the warnings / errors, you can add a list of error really fatal, and a list about just warning . Else you can add an option to throw error for each warnings returns by exiftool .

So, If a developper need to get 0 warning, he can set this option to true, and check manually warnings after .  Maybe adding a .getWarnings function to the exifTool object ? to returns all the warnings / error ( and if not in your lists, tell to open an issue with files/code to reproduce )

**Comment by thib3113** [comment]
about your code before, it's doesn't work for me . 

I always get the error :/

**Comment by mceachen** [comment]
What node version are you using, and what OS?

**Comment by thib3113** [comment]
node V10.4.0
on windows 10 v1803

**Comment by mceachen** [comment]
Try deleting your ExifTool `par` cache, located in `~/AppData/Local/Temp/par-*`.

I just ran the following on my windows 10.0.17134 box running node 10.9.0:

```js
$ node
> const ExifTool = require("exiftool-vendored").ExifTool
undefined
> const et = new ExifTool({minorErrorsRegExp:  /error|warning/i})
undefined
> et.rewriteAllTags("AFS2018-223.JPG", "repaired.jpg").then(console.dir)
Promise {
  <pending>,
  domain:
   Domain {
     domain: null,
     _events:
      { removeListener: [Function: updateExceptionCapture],
        newListener: [Function: updateExceptionCapture],
        error: [Function: debugDomainError] },
     _eventsCount: 3,
     _maxListeners: undefined,
     members: [] } }
> et.write("repaired.jpg", {AllDates: "2018:08:18 12:39:39"}).then(console.dir).catch(console.dir)
Promise {
  <pending>,
  domain:
   Domain {
     domain: null,
     _events:
      { removeListener: [Function: updateExceptionCapture],
        newListener: [Function: updateExceptionCapture],
        error: [Function: debugDomainError] },
     _eventsCount: 3,
     _maxListeners: undefined,
     members: [] } }
> undefined
undefined
mrm@xps15:/tmp/test$ exiftool.exe -j repaired.jpg | grep Date
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
        LC_ALL = "en_US.UTF-8",
        LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the system default locale ("English_United States.1252").
  "FileModifyDate": "2018:08:18 14:05:18-07:00",
  "FileAccessDate": "2018:08:18 14:05:18-07:00",
  "FileCreateDate": "2018:08:18 14:02:51-07:00",
  "ModifyDate": "2018:08:18 12:39:39",
  "DateTimeOriginal": "2018:08:18 12:39:39",
  "CreateDate": "2018:08:18 12:39:39",
  "SonyDateTime": "2018:08:14 12:36:58",
  "SonyDateTime2": "2018:08:14 10:36:59",
```

**Comment by thib3113** [comment]
I've done the process one time, but maybe to fast, I get an error because cache doesn't exist .

So, I retry a second time, and get the error : 
```sh
C:\Users\thib3\repos\timer-correct
λ node
> const ExifTool = require("exiftool-vendored").ExifTool
undefined
> const et = new ExifTool({minorErrorsRegExp:  /error|warning/i})
undefined
> et.rewriteAllTags("AFS2018-223.JPG", "repaired.jpg").then(console.dir)
Promise {
  <pending>,
  domain:
   Domain {
     domain: null,
     _events:
      { removeListener: [Function: updateExceptionCapture],
        newListener: [Function: updateExceptionCapture],
        error: [Function: debugDomainError] },
     _eventsCount: 3,
     _maxListeners: undefined,
     members: [] } }
> BatchProcess(18636).onError() { source: 'stderr.data',
  task:
   '-all=\n-tagsfromfile\n@\n-all:all\n-unsafe\n-icc_profile\nC:\\Users\\thib3\\repos\\timer-correct\\AFS2018-223.JPG\n-out\nC:\\Users\\thib3\\repos\\timer-correct\\repaired.jpg\n-ignoreMinorErrors\n-execute\n',
  error:
   Error: stderr.data: Warning: Bad offset for InteropIFD InteropIndex - C:/Users/thib3/repos/timer-correct/AFS2018-223.JPG
       at BatchProcess.<anonymous> (C:\Users\thib3\repos\timer-correct\node_modules\batch-cluster\dist\BatchProcess.js:312:25)
       at step (C:\Users\thib3\repos\timer-correct\node_modules\batch-cluster\dist\BatchProcess.js:32:23)
       at Object.next (C:\Users\thib3\repos\timer-correct\node_modules\batch-cluster\dist\BatchProcess.js:13:53)
       at C:\Users\thib3\repos\timer-correct\node_modules\batch-cluster\dist\BatchProcess.js:7:71
       at new Promise (<anonymous>)
       at __awaiter (C:\Users\thib3\repos\timer-correct\node_modules\batch-cluster\dist\BatchProcess.js:3:12)
       at BatchProcess.onError (C:\Users\thib3\repos\timer-correct\node_modules\batch-cluster\dist\BatchProcess.js:306:16)
       at Socket.<anonymous> (C:\Users\thib3\repos\timer-correct\node_modules\batch-cluster\dist\BatchProcess.js:81:26)
       at Socket.emit (events.js:182:13)
       at Socket.EventEmitter.emit (domain.js:460:23) }
undefined
```

**Comment by mceachen** [comment]
I finally took a look at your problematic image, and it's been truncated. There's no saving that file, I'm afraid.

```sh
jpegtran -outfile /dev/null ~/Downloads/AFS2018-223.JPG 
Corrupt JPEG data: premature end of data segment
Unsupported marker type 0xa9
```

I did just publish version 6.1.2 which suppresses the console error messages, but in this case, even running a metadata repair won't fix the corrupt image.

**Comment by thib3113** [comment]
Yes, It's what I think too :/ .
