### ISSUE TITLE
gps.toDate is not a function

### ISSUE THREAD

**Issue by Christian24** [mceachen/exiftool-vendored.js#3]
Hello,

I am having trouble with the package. This is the issue I am getting when trying to read exif data:
```
TypeError: gps.toDate is not a function
    at TagsTask.extractTzoffset (E:\photos\node_modules\exiftool-vendored\dist\tags_task.js:64:41)
    at TagsTask.parseTags (E:\photos\node_modules\exiftool-vendored\dist\tags_task.js:72:14)
    at TagsTask.parse (E:\photos\node_modules\exiftool-vendored\dist\tags_task.js:46:21)
    at TagsTask.Task.onData (E:\photos\node_modules\exiftool-vendored\dist\task.js:26:31)
    at ExifToolProcess.onData (E:\photos\node_modules\exiftool-vendored\dist\exiftool_process.js:137:22)
    at Socket.<anonymous> (E:\photos\node_modules\exiftool-vendored\dist\exiftool_process.js:40:65)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
```
I am on node 6.10.0.

Thanks a lot,
Christian

**Comment by mceachen** [comment]
Could you attach that file's tags? Something like

```sh
exiftool -j file.jpg > file-to-attach.json
```

**Comment by mceachen** [comment]
Assuming the GPS tag contents are invalid, I put guards around the values and added a breaking test, and pushed v2.12.0 with this fix. Please attach the tag contents even though this ticket is closed, and holler if this diff didn't fix it.
